### ISSUE TITLE
Update abstractor:setup:stanford_core_nlp to install latest version of Stanford CoreNLP.

### ISSUE THREAD

**Issue by mgurley** [NUBIC/abstractor#103]
Here is the link to the latest install: http://nlp.stanford.edu/software/stanford-corenlp-full-2015-04-20.zip

**Comment by ybushmanova** [comment]
Got the latest version of the gem to test specs, getting the following error from all abstraction specs:

UnsupportedClassVersionError:
       edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0

Any ideas?

**Comment by mgurley** [comment]
Did you regenerate the testbed?

**Comment by ybushmanova** [comment]
Yes. I did a clean checkout into a new folder and regenerated the testbed.

**Comment by mgurley** [comment]
You might need to upgrade Java.  Do a java -version and see what you are
running?

**Comment by ybushmanova** [comment]
$ java -version
java version "1.7.0_71"

**Comment by mgurley** [comment]
Ok, I am running 1.8.0_31.  I think the latest version of Stanford must
have been compiled against 1.8.  Install the JDK and it should upgrade you
to 1.8.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by ybushmanova** [comment]
This worked, thanks!
