### ISSUE TITLE
Add support for custom NLP suggestion providers.

### ISSUE THREAD

**Issue by mgurley** [NUBIC/abstractor#82]
Sometimes Abstractor's native NLP capabilities will not be good enough.  So we would like to be able to outsource the job of generating suggestions against narrative text to an external NLP library.  Here is the plan:

* Add new source type 'custom nlp suggestion'.
* Add new column 'custom_nlp_provider' to abstractor_abstraction_sources.
* Assume all communication between the custom nlp provider and abstractor will be done over HTTPS.
* Add a new rake task to setup a yml configuration per environment in the host application at config/abstractor/custom_nlp_providers.yml.  The yml file will contain an endpoint for each configured provider like so:
```
custom_nlp_provider_name:
  suggestion_endpoint:
      development: http://custom-nlp-provider.dev/suggest
      test: http://custom-nlp-provider.test/suggest
      staging: http://custom-nlp-provider-staging.org/suggest
      production: http://custom-nlp-provider.org/suggest
```
* Abstractor will expose a resource listing abstraction schemas: /abstractor_abstraction_schemas/
* Abstractor will expose a resource exposing the details of an abstraction schema:  /abstractor_abstraction_schemas/1/.  This resource will expose the schema's predicate, display name, object type, preferred name, object values and object value variants.
* During the abstraction process, if an abstraction source has a source type of 'custom nlp suggestion' , Abstractor will use the name of the provider in the custom_nlp_provider column and look up the endpoint in its current environment.   Abstractor will post to the provider's endpoint a unique identifier of the abstraction schema, a unique identifier of the abstraction, a unique identifier of the abstraction source and the textual content.  Abstractor might pass object values and object value variants if we decide synchronization between the external library and Abstractor is too much overhead.
* Here is a rough draft of the JSON message that will be posted by Abstractor to the provider's configured endpoint:
```
{
  "abstractor_abstraction_schema_id":1,
  "abstractor_abstraction_id":1,
  "abstractor_abstraction_source_id":1,
  "source_type":  "PathologyCase",
  "source_method": "note_text",
  "text": "The patient has a diagnosis of glioblastoma.  GBM does not have a good prognosis.  But I can't rule out meningioma.",
  "object_values": [
    { "value": "glioblastoma, nos",
      "object_value_variants":[
        { "value": "glioblastoma" },
        { "value": "gbm" },
        { "value": "spongioblastoma multiforme"}
      ]
    },
    { "value": "meningioma, nos",
      "object_value_variants":[
        { "value": "meningioma" },
        { "value": "leptomeningioma" },
        { "value": "meningeal fibroblastoma" }
      ]
    }
  ]
}
```
*  The provider will be expected to generate suggestions and invoke an endpoint provided by Abstractor to insert a suggestion and its suggestion sources: /abstractor_abstractions/1/abstractor_suggestions/.  The endpoint will expect a post with a JSON message in the following format:
```
{
   "abstractor_suggestion":{
      "abstractor_abstraction_source_id":1,
      "source_id":1,
      "source_type": "PathologyCase",
      "source_method": "note_text",
      "value":"glioblastoma",
      "unknown":null,
      "not_applicable":null,
      "suggestion_sources":[
                  {
                  "match_value":"glioblastoma",
                  "sentence_match_value":"The patient has a diagnosis of glioblastoma."
               },
               {
                  "match_value":"gbm",
                  "sentence_match_value":"GBM does not have a good prognosis."
               }
            ]
   }
}
```
* If the provider wants to make more than one suggestion, then it will need to invoke the endpoint again with a new suggestion:
```
{
   "abstractor_suggestion":{
      "abstractor_abstraction_source_id":1,
      "source_id":1,
      "source_type": "PathologyCase",
      "source_method": "note_text",
      "value":"meningioma",
      "unknown":null,
      "not_applicable":null,
      "sources":[
         {
            "match_value":"meningioma",
            "sentence_match_value":"But I can't rule out meningioma."
         }
      ]
   }
}
```

**Comment by sidkgp** [comment]
Thanks Mike, I read the JSON templates and get what’s going on. This would be something that should be relatively straightforward to generate from an existing NLP tool.

**Comment by leolincoln** [comment]
Cool it seems we can help add on using this. Could you give an example of how we can post our to http://custom-nlp-provider-staging.org/suggest ? Currently our format is just documentID -> Dictionary of multiple (organ, stage) pairs.
