### ISSUE TITLE
Add support for sentinental groups

### ISSUE THREAD

**Issue by ybushmanova** [NUBIC/abstractor#98]
Allow to mark a subject group as sentinental. Regroup abstractions in sentinental groups so that each abstraction group contains suggestions from the same sentence.

**Comment by mgurley** [comment]
Can you add the subtype possible values to Abstractor::Enum?

**Comment by mgurley** [comment]
I am getting a failing spec

 1) EncounterNote abstracting grouped abstractions leaves one group if no sentinental subgroups detected
     Failure/Error: expect(abstractor_suggestion_sources.select(:sentence_match_value).distinct.map(&:sentence_match_value).length).to eq 1
       
       expected: 1
            got: 0
       
       (compared using ==)
     # ./spec/models/abstractor/encounter_note_spec.rb:719:in `block (5 levels) in <top (required)>'
     # ./spec/models/abstractor/encounter_note_spec.rb:713:in `block (4 levels) in <top (required)>'
